In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r"C:\Users\santo\OneDrive\Dokumen\DiBimbing\BIG PROJECT\DataCo SMART SUPPLY CHAIN FOR BIG DATA ANALYSIS\DataCoSupplyChainDataset.csv", encoding='latin1')

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [5]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [6]:
print("Rows and Columns:")
print(df.shape)

Rows and Columns:
(180519, 53)

In [7]:
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 73.0 MB

In [9]:
missing_values = df.isnull().sum()

missing_values[missing_values > 0].sort_values(ascending=False)

Product Description    180519
Order Zipcode          155679
Customer Lname              8
Customer Zipcode            3
dtype: int64

In [10]:
duplicates = df.duplicated().sum()

print(f"Duplicate Rows: {duplicates}")

Duplicate Rows: 0

In [11]:
df = df.drop_duplicates()

print("Duplicates Removed")

Duplicates Removed

In [12]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "")
    .str.replace(")", "")
)

df.columns

Index(['type', 'days_for_shipping_real', 'days_for_shipment_scheduled',
       'benefit_per_order', 'sales_per_customer', 'delivery_status',
       'late_delivery_risk', 'category_id', 'category_name', 'customer_city',
       'customer_country', 'customer_email', 'customer_fname', 'customer_id',
       'customer_lname', 'customer_password', 'customer_segment',
       'customer_state', 'customer_street', 'customer_zipcode',
       'department_id', 'department_name', 'latitude', 'longitude', 'market',
       'order_city', 'order_country', 'order_customer_id',
       'order_date_dateorders', 'order_id', 'order_item_cardprod_id',
       'order_item_discount', 'order_item_discount_rate', 'order_item_id',
       'order_item_product_price', 'order_item_profit_ratio',
       'order_item_quantity', 'sales', 'order_item_total',
       'order_profit_per_order', 'order_region', 'order_state', 'order_status',
       'order_zipcode', 'product_card_id', 'product_category_id',
       'product_description', 'product_image', 'product_name', 'product_price',
       'product_status', 'shipping_date_dateorders', 'shipping_mode'],
      dtype='str')

In [13]:
date_columns = [col for col in df.columns if 'date' in col]

print(date_columns)

['order_date_dateorders', 'shipping_date_dateorders']

In [14]:
for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors='coerce')

print("Date Conversion Complete")

Date Conversion Complete

In [15]:
df[date_columns].head()

  order_date_dateorders shipping_date_dateorders
0   2018-01-31 22:56:00      2018-02-03 22:56:00
1   2018-01-13 12:27:00      2018-01-18 12:27:00
2   2018-01-13 12:06:00      2018-01-17 12:06:00
3   2018-01-13 11:45:00      2018-01-16 11:45:00
4   2018-01-13 11:24:00      2018-01-15 11:24:00

In [16]:
df = df.rename(columns={
    'order_date_dateorders': 'order_date',
    'shipping_date_dateorders': 'shipping_date'
})

In [19]:
df[['order_date', 'shipping_date']].head()

           order_date       shipping_date
0 2018-01-31 22:56:00 2018-02-03 22:56:00
1 2018-01-13 12:27:00 2018-01-18 12:27:00
2 2018-01-13 12:06:00 2018-01-17 12:06:00
3 2018-01-13 11:45:00 2018-01-16 11:45:00
4 2018-01-13 11:24:00 2018-01-15 11:24:00

In [20]:
df.isnull().sum().sort_values(ascending=False).head(20)

product_description            180519
order_zipcode                  155679
customer_lname                      8
customer_zipcode                    3
days_for_shipment_scheduled         0
sales_per_customer                  0
benefit_per_order                   0
delivery_status                     0
late_delivery_risk                  0
customer_city                       0
customer_country                    0
category_id                         0
category_name                       0
customer_fname                      0
customer_email                      0
customer_password                   0
customer_id                         0
customer_segment                    0
customer_state                      0
days_for_shipping_real              0
dtype: int64

Drop High Missing Columns

In [21]:
df = df.drop(columns=[
    'product_description',
    'order_zipcode'
])

print("High Missing Columns Dropped")

High Missing Columns Dropped

Fill Remaining Missing Values

In [ ]:
#Numerical Columns - Fill with Median

num_cols = df.select_dtypes(include=np.number).columns

df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [ ]:
#Categorical Columns - Fill with 'Unknown'

cat_cols = df.select_dtypes(include='object').columns

df[cat_cols] = df[cat_cols].fillna('Unknown')

C:\Users\santo\AppData\Local\Temp\ipykernel_39020\779871898.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include='object').columns

Check Missing Again

In [25]:
#Check Missing Again
df.isnull().sum().sort_values(ascending=False).head(20)

type                           0
days_for_shipping_real         0
days_for_shipment_scheduled    0
benefit_per_order              0
sales_per_customer             0
delivery_status                0
late_delivery_risk             0
category_id                    0
category_name                  0
customer_city                  0
customer_country               0
customer_email                 0
customer_fname                 0
customer_id                    0
customer_lname                 0
customer_password              0
customer_segment               0
customer_state                 0
customer_street                0
customer_zipcode               0
dtype: int64

Rename Kolom Penting

Supaya:

SQL lebih gampang
Tableau lebih rapi
coding lebih professional

In [26]:
df = df.rename(columns={
    'order_date_dateorders': 'order_date',
    'shipping_date_dateorders': 'shipping_date'
})

print("Columns Renamed Successfully")

Columns Renamed Successfully

In [27]:
df[['order_date', 'shipping_date']].head()

           order_date       shipping_date
0 2018-01-31 22:56:00 2018-02-03 22:56:00
1 2018-01-13 12:27:00 2018-01-18 12:27:00
2 2018-01-13 12:06:00 2018-01-17 12:06:00
3 2018-01-13 11:45:00 2018-01-16 11:45:00
4 2018-01-13 11:24:00 2018-01-15 11:24:00

Feature Engineering

Sekarang kita buat kolom baru yang sangat penting untuk analytics

In [28]:
df['delivery_days'] = (
    df['shipping_date'] - df['order_date']
).dt.days

In [29]:
df[['order_date', 'shipping_date', 'delivery_days']].head()

           order_date       shipping_date  delivery_days
0 2018-01-31 22:56:00 2018-02-03 22:56:00              3
1 2018-01-13 12:27:00 2018-01-18 12:27:00              5
2 2018-01-13 12:06:00 2018-01-17 12:06:00              4
3 2018-01-13 11:45:00 2018-01-16 11:45:00              3
4 2018-01-13 11:24:00 2018-01-15 11:24:00              2

Tambahan Feature Engineering Professional
Profit Margin (%)

Ini bagus banget buat Tableau & insight bisnis.

In [30]:
df['profit_margin'] = (
    df['benefit_per_order'] / df['sales_per_customer']
) * 100

Bersihkan Infinity / Error

Kadang ada pembagian 0.

In [31]:
df['profit_margin'] = df['profit_margin'].replace(
    [np.inf, -np.inf],
    np.nan
)

df['profit_margin'] = df['profit_margin'].fillna(0)

In [32]:
df[['sales_per_customer', 'benefit_per_order', 'profit_margin']].head()

   sales_per_customer  benefit_per_order  profit_margin
0          314.640015          91.250000      29.001397
1          311.359985        -249.089996     -80.000645
2          309.720001        -247.779999     -80.001291
3          304.809998          22.860001       7.499754
4          298.250000         134.210007      44.999164

Final Check

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   type                         180519 non-null  str
 1   days_for_shipping_real       180519 non-null  int64
 2   days_for_shipment_scheduled  180519 non-null  int64
 3   benefit_per_order            180519 non-null  float64
 4   sales_per_customer           180519 non-null  float64
 5   delivery_status              180519 non-null  str
 6   late_delivery_risk           180519 non-null  int64
 7   category_id                  180519 non-null  int64
 8   category_name                180519 non-null  str
 9   customer_city                180519 non-null  str
 10  customer_country             180519 non-null  str
 11  customer_email               180519 non-null  str
 12  customer_fname               180519 non-null  str
 13  customer_id                  180519 non-null  int64
 14  customer_lname               180519 non-null  str
 15  customer_password            180519 non-null  str
 16  customer_segment             180519 non-null  str
 17  customer_state               180519 non-null  str
 18  customer_street              180519 non-null  str
 19  customer_zipcode             180519 non-null  float64
 20  department_id                180519 non-null  int64
 21  department_name              180519 non-null  str
 22  latitude                     180519 non-null  float64
 23  longitude                    180519 non-null  float64
 24  market                       180519 non-null  str
 25  order_city                   180519 non-null  str
 26  order_country                180519 non-null  str
 27  order_customer_id            180519 non-null  int64
 28  order_date                   180519 non-null  datetime64[us]
 29  order_id                     180519 non-null  int64
 30  order_item_cardprod_id       180519 non-null  int64
 31  order_item_discount          180519 non-null  float64
 32  order_item_discount_rate     180519 non-null  float64
 33  order_item_id                180519 non-null  int64
 34  order_item_product_price     180519 non-null  float64
 35  order_item_profit_ratio      180519 non-null  float64
 36  order_item_quantity          180519 non-null  int64
 37  sales                        180519 non-null  float64
 38  order_item_total             180519 non-null  float64
 39  order_profit_per_order       180519 non-null  float64
 40  order_region                 180519 non-null  str
 41  order_state                  180519 non-null  str
 42  order_status                 180519 non-null  str
 43  product_card_id              180519 non-null  int64
 44  product_category_id          180519 non-null  int64
 45  product_image                180519 non-null  str
 46  product_name                 180519 non-null  str
 47  product_price                180519 non-null  float64
 48  product_status               180519 non-null  int64
 49  shipping_date                180519 non-null  datetime64[us]
 50  shipping_mode                180519 non-null  str
 51  delivery_days                180519 non-null  int64
 52  profit_margin                180519 non-null  float64
dtypes: datetime64[us](2), float64(14), int64(15), str(22)
memory usage: 73.0 MB

In [34]:
df.isnull().sum().sort_values(ascending=False).head(10)

type                           0
days_for_shipping_real         0
days_for_shipment_scheduled    0
benefit_per_order              0
sales_per_customer             0
delivery_status                0
late_delivery_risk             0
category_id                    0
category_name                  0
customer_city                  0
dtype: int64

In [36]:
df.to_csv(
    "C:\\Users\\santo\\OneDrive\\Dokumen\\DiBimbing\\BIG PROJECT\\Data Cleaned\\supply_chain_cleaned.csv",
    index=False
)

print("Clean Dataset Saved Successfully")

Clean Dataset Saved Successfully